// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKrHaWRaKnIO-A25-RJEMGpN_5n8fPDCM',
    appId: '1:422973110695:web:25449bcef04e62b9631e82',
    messagingSenderId: '422973110695',
    projectId: 'scientific-research-8949f',
    authDomain: 'scientific-research-8949f.firebaseapp.com',
    storageBucket: 'scientific-research-8949f.firebasestorage.app',
    measurementId: 'G-RWBRN177XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmmPMNdCKsfeQpLVsx__cwqA44XV5xjUA',
    appId: '1:422973110695:android:d47f6e255748ff46631e82',
    messagingSenderId: '422973110695',
    projectId: 'scientific-research-8949f',
    storageBucket: 'scientific-research-8949f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4oMsi44xutlsTO9J4XEICxLQEvByvrg',
    appId: '1:422973110695:ios:81e6c41a2d8597ff631e82',
    messagingSenderId: '422973110695',
    projectId: 'scientific-research-8949f',
    storageBucket: 'scientific-research-8949f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM4oMsi44xutlsTO9J4XEICxLQEvByvrg',
    appId: '1:422973110695:ios:81e6c41a2d8597ff631e82',
    messagingSenderId: '422973110695',
    projectId: 'scientific-research-8949f',
    storageBucket: 'scientific-research-8949f.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKrHaWRaKnIO-A25-RJEMGpN_5n8fPDCM',
    appId: '1:422973110695:web:e126c5deedc8b232631e82',
    messagingSenderId: '422973110695',
    projectId: 'scientific-research-8949f',
    authDomain: 'scientific-research-8949f.firebaseapp.com',
    storageBucket: 'scientific-research-8949f.firebasestorage.app',
    measurementId: 'G-6QDP2WTEF0',
  );
}
